/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

#ifndef _APL_SESSION_H
#define _APL_SESSION_H

#include "apl/common.h"
#include "apl/primitives/object.h"
#include "apl/utils/log.h"

namespace apl {

/**
 * A message generated by the Log command, originating from the APL document author.
 */
struct LogCommandMessage {
    std::string text;   // Command-specified message text
    LogLevel level;     // Command-specified log level
    Object arguments;   // Command-specified additional arguments
    Object origin;      // Event handler source, for tracking provenance
};

/**
 * The Session object provides a virtual console to report errors and problems that occur when
 * parsing the APL document and packages.  These are the errors that should be reported back to
 * the APL content author.
 *
 * Each view host should provide a custom Session object per logical displayed document.
 * If no session object is provided, console errors will be written to the standard log.
 *
 * Remember!  If the error is something the APL author should correct, report it on the CONSOLE
 * macros below and it should be routed to the APL author.  If the error is something inside
 * of the APL Core Library, report it using LOG.
 */
class Session {
public:
    Session();
    virtual ~Session() = default;

    /**
     * Write a string in the session log, including the filename and function where
     * the log was generated.
     *
     * Override this method in your Session subclass.
     *
     * @param filename The name of the file where the console message was generated
     * @param func The name of the function where the console message was generated
     * @param value The string to write
     */
    virtual void write(const char *filename, const char *func, const char *value) = 0;

    /**
     * Write a string in the session log, including the filename and function where
     * the log was generated.  This is a convenience method for std::string
     *
     * @param filename The filename where the log entry was generated.
     * @param func The function mame where the log entry was generated.
     * @param value The message to write
     */
    void write(const char *filename, const char *func, const std::string& value) {
        write(filename, func, value.c_str());
    }

    /**
     * Report a log message resulting from execution of the Log command. The view host is
     * responsible for reporting this information to the APL document author when a valid debugging
     * context is available. When a valid debugging context is not available, the entry should be
     * discarded, since it could contain arbitrary customer information from the APL document's
     * execution context.
     *
     * By default, the log message is discarded.
     *
     * @param message The log command message payload
     */
    virtual void write(LogCommandMessage&& message) {}

    /**
     * Set log prefix to be used.
     * @param prefix [A-Z], truncated to 6 characters. Padded with '_'
     */
    void setLogIdPrefix(const std::string& prefix);

    /**
     * @return Generated Log ID.
     */
    std::string getLogId() const {
        return mLogId;
    }

private:
    std::string mLogId;
};

/**
 * Construct a default session which passes console messages to the log.  The default session
 * writes session messages to the log as warnings.
 * @return A default session pointer.
 */
extern SessionPtr makeDefaultSession();

/**
 * Temporary object used to accumulate logging information before writing it to the session.
 */
class SessionMessage {
public:
    SessionMessage(const SessionPtr& session, const char *filename, const char *function);

    SessionMessage(const ContextPtr& contextPtr, const char *filename, const char *function);

    SessionMessage(const Context& context, const char *filename, const char *function);

    SessionMessage(const std::weak_ptr<Context>& contextPtr, const char *filename, const char *function);

    SessionMessage(const ContentPtr& content, const char *filename, const char *function);

    SessionMessage(const CoreDocumentContextPtr& document, const char *filename, const char *function);

    ~SessionMessage();

    template<class T> friend SessionMessage& operator<<(SessionMessage&& sm, T&& value)
    {
        sm.mStringStream << std::forward<T>(value);
        return sm;
    }

    template<class T> friend SessionMessage& operator<<(SessionMessage& sm, T&& value)
    {
        sm.mStringStream << std::forward<T>(value);
        return sm;
    }

    template<class T> friend SessionMessage& operator<<(SessionMessage& sm, const std::vector<T>& values)
    {
        auto len = values.size();
        for (auto i = 0 ; i < len ; i++) {
            sm.mStringStream << values.at(i);
            if (i < len - 1)
                sm.mStringStream << "/";
        }
        return sm;
    }

    /**
     * @param format Log message format. Same format as for printf.
     * @param ... Variable arguments.
     */
    SessionMessage& log(const char *format, ...);

private:
    SessionPtr mSession;
    std::string mFilename;
    std::string mFunction;

    const bool mUncaught;
    streamer mStringStream;
};

#define CONSOLE(SESSION_HOLDER) SessionMessage(SESSION_HOLDER,__FILENAME__,__func__)

} // namespace apl

#endif // _APL_SESSION_H
